### ISSUE TITLE
The homebrew tap is deprecated for latest Homebrew

### ISSUE THREAD

**Issue by xdqi** [jlhonora/lsusb#10]
When I was `brew update`-ing my system, I got a message reads like below.

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jlhonora/homebrew-lsusb/lsusb.rb:8:in `<class:Lsusb>'
```

Please update the checksum algorithm to SHA256 to avoid this problem.

**Comment by jlhonora** [comment]
Thanks, closed via https://github.com/jlhonora/homebrew-lsusb/pull/2
