### ISSUE TITLE
missing manufacturer from the -t option

### ISSUE THREAD

**Issue by dardo82** [jlhonora/lsusb#8]
Why there is no manufacturer's name in the output of the "tree" option?

**Comment by johnfreed** [comment]
lsusb is a clone of the Linux function. If you want an enhancement there
are two routes:
1) ask the Linux maintainers to add it
2) write a new switch with the enhancement (see the parens switch as an
example)

Your chance of success with #1 is probably low.

**Comment by dardo82** [comment]
Have you seen the related commit from my fork?
Could you please merge it? (https://github.com/dardo82/lsusb/commit/23a3055ae1d2424379630e93d39d564f0a7efdcd)

**Comment by johnfreed** [comment]
Well just glancing at it I believe it changes the function of the -t
switch. Perhaps you could rewrite using for example a -T switch

**Comment by jlhonora** [comment]
As John says, this repo tries to emulate lsusb's functionality as close as what the Linux version does. If you use an unused flag (such as `-T`) I'd be glad to merge it, but:
1. If another function using -T is added in Linux then we'll probably change this one.
2. Please add documentation on what is its expected output.

Thanks in advance.

**Comment by dardo82** [comment]
So there is no manufacturer in the tree option's output in the linux version? I'm using OS X at the moment,so i don't know it for sure,as i don't know why they should add a new option in the future. 
Anyway i think i'll try to see if can add the option separately and update the man page too,ok? 8-)

**Comment by jlhonora** [comment]
Yes, no manufacturer in `-t`. As for the separate switch, that'd be great.

**Comment by dardo82** [comment]
I have updated the pull request https://github.com/jlhonora/lsusb/pull/9. Can you please review it?
